<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Tools.Sample\Tools.Sample.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Serilog" Version="3.1.1" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
  </ItemGroup>

  <Target Name="CopyToolsOnBuild" AfterTargets="Build">
    <MakeDir Directories="$(OutDir)tools" />
    <Copy SourceFiles="..\Tools.Sample\bin\$(Configuration)\net8.0\Tools.Sample.dll" DestinationFolder="$(OutDir)tools" SkipUnchangedFiles="true" Condition="Exists('..\Tools.Sample\bin\$(Configuration)\net8.0\Tools.Sample.dll')" />
  </Target>

  <Target Name="CopyToolsOnPublish" AfterTargets="Publish">
    <MakeDir Directories="$(PublishDir)tools" />
    <Copy SourceFiles="..\Tools.Sample\bin\$(Configuration)\net8.0\Tools.Sample.dll" DestinationFolder="$(PublishDir)tools" SkipUnchangedFiles="true" Condition="Exists('..\Tools.Sample\bin\$(Configuration)\net8.0\Tools.Sample.dll')" />
  </Target>
</Project>
